schema_version: 1

context:
  name: kanidm-clients
  version: "1.9.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/kanidm/kanidm/archive/refs/tags/v${{ version | replace("rc", "-rc.") }}.tar.gz
  sha256: 55cdbc423a5f910ecde91db80e32c8536add25abec210764fe1d1bf1427f26b5

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - lld
    - cargo-bundle-licenses
    - pkg-config
    - openssl
    - if: linux
      then: libudev
  host:
    - if: linux
      then: libudev
    - openssl

tests:
  - script:
      - kanidm version

about:
  summary: A simple, secure and fast identity management platform
  description: |
    Kanidm is a simple and secure identity management platform, allowing other applications and services to offload the challenge of authenticating and storing identities to Kanidm.
    The goal of this project is to be a complete identity provider, covering the broadest possible set of requirements and integrations. You should not need any other components (like Keycloak) when you use Kanidm - we already have everything you need!
    To achieve this we rely heavily on strict defaults, simple configuration, and self-healing components. This allows Kanidm to run from small home labs, families, small business, and all the way to the largest enterprise needs.
    If you want to host your own authentication service, then Kanidm is for you!
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - THIRDPARTY_LICENSES.yaml
  homepage: https://kanidm.com/
  repository: https://github.com/kanidm/kanidm
  documentation: https://kanidm.github.io/kanidm/stable/

extra:
  recipe-maintainers:
    - freundTech
